### ISSUE TITLE
Original and Yours

### ISSUE THREAD

**Issue by jobdiogenes** [danielwagn3r/dans-dbf-lib#2]
Hello,

I'm looking to use this dans-dbf-lib in Dbeaver, and found  
 the original and yours, which was based in sourceforge, and not forked from github.
I saw that you make many changes. Bug fixes and  maybe news features. 
If you add news features, what was?

**Comment by danielwagn3r** [comment]
Hi,

I've added a feature reguarding quotestyle, see https://sourceforge.net/u/kwaxi/csvjdbc/ci/master/tree/

The upstream author didn't accept my pull requests so I gave up using this library.
